version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
  azurite:
    container_name: "${AZURITE_DOCKER_NAME-azurite}"
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "127.0.0.1:10000:10000"
  fake-gcs-server:
    container_name: "${FAKE_GCS_DOCKER_NAME-fake_gcs_server}"
    image: fsouza/fake-gcs-server
    command: ["-scheme", "http", "-port", "4443"]
    ports:
      - "127.0.0.1:4443:4443"
