name: OasisDataManager Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      odm_branch:
        description: 'Build package from branch'
        required: false
        type: string
    outputs:
      src_filename:
        description: "Source Package filename"
        value: ${{ jobs.build.outputs.src_filename }}
      whl_filename:
        description: "Wheel Package filename"
        value: ${{ jobs.build.outputs.whl_filename }}

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    outputs:
      src_filename: ${{ steps.build_package.outputs.source }}
      whl_filename: ${{ steps.build_package.outputs.wheel }}

    steps:
    - name: Github context
      run:   echo "$GITHUB_CONTEXT"
      shell: bash
      env:
       GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Clone
      uses: actions/checkout@v3
      if: inputs.odm_branch == ''
      with:
        repository: OasisLMF/OasisDataManager

    - name: Clone (workflow_call)
      uses: actions/checkout@v3
      if: inputs.odm_branch != ''
      with:
        repository: OasisLMF/OasisDataManager
        ref: ${{ inputs.odm_branch }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install pip-tools wheel

    - name: Create package
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Build Output
      id: build_package
      run: |
        WHL=$(find ./dist/ -name "*.whl"  -exec basename {} \;)
        SRC=$(find ./dist/ -name "*.tar.gz"  -exec basename {} \;)
        echo "wheel=$WHL" >> $GITHUB_OUTPUT
        echo "source=$SRC" >> $GITHUB_OUTPUT

    - name: Store source package
      uses: actions/upload-artifact@v3
      with:
        name: odm_src_package
        path: ./dist/${{ steps.build_package.outputs.source }}
        retention-days: 5

    - name: Store Wheel package
      uses: actions/upload-artifact@v3
      with:
        name: odm_bin_package
        path: ./dist/${{ steps.build_package.outputs.wheel }}
        retention-days: 5
